import { collection, doc, writeBatch } from 'firebase/firestore';
import { db, cleanFirestoreData } from './firebase';
import {
  School,
  AcademicSession,
  ClassItem,
  SectionItem,
  SubjectItem,
  Student,
  StaffMember,
  FinancialSettings,
  FeeStructure,
  FeeDiscount,
  FeeItem,
  FeePayment,
  Receipt,
  Expense,
  ExpenseCategory,
  CashBookEntry,
} from '../types';
import { logAuditEvent } from './auditService';

export async function loadDemoSchoolData(schoolId: string, adminUserId: string, adminName: string): Promise<void> {
  const batch = writeBatch(db);
  const now = new Date().toISOString();

  // 1. Academic Session
  const sessionId = `session_demo_2025_26`;
  const session: AcademicSession = {
    id: sessionId,
    schoolId,
    name: '2025-26',
    startDate: '2025-04-01',
    endDate: '2026-03-31',
    isActive: true,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  };
  batch.set(doc(db, 'academicSessions', sessionId), cleanFirestoreData(session));

  // 2. Classes: Class 9, Class 10, Class 11
  const classDefs = [
    { id: 'class_demo_c9', name: 'Class 9', code: 'C09' },
    { id: 'class_demo_c10', name: 'Class 10', code: 'C10' },
    { id: 'class_demo_c11', name: 'Class 11', code: 'C11' },
  ];

  classDefs.forEach((c) => {
    const classData: ClassItem = {
      id: c.id,
      schoolId,
      name: c.name,
      code: c.code,
      sessionId,
      capacity: 60,
      status: 'ACTIVE',
      createdAt: now,
      updatedAt: now,
    };
    batch.set(doc(db, 'classes', c.id), cleanFirestoreData(classData));
  });

  // 3. Sections: A, B for each class
  const sectionDefs: { id: string; classId: string; name: string; room: string }[] = [];
  classDefs.forEach((c) => {
    sectionDefs.push({
      id: `sec_demo_${c.code}_A`,
      classId: c.id,
      name: 'A',
      room: `Room ${c.code}-1`,
    });
    sectionDefs.push({
      id: `sec_demo_${c.code}_B`,
      classId: c.id,
      name: 'B',
      room: `Room ${c.code}-2`,
    });
  });

  sectionDefs.forEach((s) => {
    const secData: SectionItem = {
      id: s.id,
      schoolId,
      classId: s.classId,
      name: s.name,
      room: s.room,
      capacity: 35,
      sessionId,
      status: 'ACTIVE',
      createdAt: now,
      updatedAt: now,
    };
    batch.set(doc(db, 'sections', s.id), cleanFirestoreData(secData));
  });

  // 4. Subjects: English, Mathematics, Science, Social Science, Hindi
  const subjectDefs = [
    { name: 'English', code: 'ENG101', type: 'CORE' as const, maxMarks: 100, passMarks: 33, isPractical: false },
    { name: 'Mathematics', code: 'MTH102', type: 'CORE' as const, maxMarks: 100, passMarks: 33, isPractical: false },
    { name: 'Science', code: 'SCI103', type: 'CORE' as const, maxMarks: 100, passMarks: 33, isPractical: true },
    { name: 'Social Science', code: 'SST104', type: 'CORE' as const, maxMarks: 100, passMarks: 33, isPractical: false },
    { name: 'Hindi', code: 'HIN105', type: 'CORE' as const, maxMarks: 100, passMarks: 33, isPractical: false },
  ];

  subjectDefs.forEach((sub, idx) => {
    const subId = `sub_demo_${idx + 1}`;
    const subData: SubjectItem = {
      id: subId,
      schoolId,
      name: sub.name,
      code: sub.code,
      type: sub.type,
      maxMarks: sub.maxMarks,
      passMarks: sub.passMarks,
      isPractical: sub.isPractical,
      assignedClassIds: classDefs.map((c) => c.id),
      status: 'ACTIVE',
      createdAt: now,
      updatedAt: now,
    };
    batch.set(doc(db, 'subjects', subId), cleanFirestoreData(subData));
  });

  // 5. Teachers: 5 teachers
  const teachers = [
    { name: 'Dr. Ramesh Chandra', empId: 'TCH-001', desig: 'Senior Math Teacher', dept: 'Mathematics', phone: '+91 9811223344', email: 'ramesh.chandra@schoolos.demo' },
    { name: 'Mrs. Sunita Verma', empId: 'TCH-002', desig: 'Science Faculty', dept: 'Science', phone: '+91 9811223345', email: 'sunita.verma@schoolos.demo' },
    { name: 'Mr. Arvind Joshi', empId: 'TCH-003', desig: 'English Teacher', dept: 'Languages', phone: '+91 9811223346', email: 'arvind.joshi@schoolos.demo' },
    { name: 'Ms. Priya Menon', empId: 'TCH-004', desig: 'Social Studies Teacher', dept: 'Social Studies', phone: '+91 9811223347', email: 'priya.menon@schoolos.demo' },
    { name: 'Mr. Alok Mishra', empId: 'TCH-005', desig: 'Hindi Faculty', dept: 'Languages', phone: '+91 9811223348', email: 'alok.mishra@schoolos.demo' },
  ];

  teachers.forEach((t, i) => {
    const tId = `staff_demo_tch_${i + 1}`;
    const staffData: StaffMember = {
      id: tId,
      schoolId,
      employeeId: t.empId,
      name: t.name,
      gender: i % 2 === 0 ? 'MALE' : 'FEMALE',
      phone: t.phone,
      email: t.email,
      designation: t.desig,
      department: t.dept,
      category: 'Teacher',
      joiningDate: '2022-07-01',
      employmentStatus: 'ACTIVE',
      assignedClassIds: [classDefs[i % classDefs.length].id],
      createdAt: now,
      updatedAt: now,
    };
    batch.set(doc(db, 'staff', tId), cleanFirestoreData(staffData));
  });

  // 6. Other Staff: 3 staff members
  const otherStaff = [
    { name: 'Vikram Singh', empId: 'STF-001', category: 'Accountant' as const, desig: 'Chief Accountant', dept: 'Accounts', phone: '+91 9811001122' },
    { name: 'Meena Rawat', empId: 'STF-002', category: 'Receptionist' as const, desig: 'Front Desk Officer', dept: 'Administration', phone: '+91 9811001123' },
    { name: 'Sanjay Kumar', empId: 'STF-003', category: 'Librarian' as const, desig: 'Head Librarian', dept: 'Library', phone: '+91 9811001124' },
  ];

  otherStaff.forEach((st, i) => {
    const sId = `staff_demo_oth_${i + 1}`;
    const staffData: StaffMember = {
      id: sId,
      schoolId,
      employeeId: st.empId,
      name: st.name,
      gender: i % 2 === 0 ? 'MALE' : 'FEMALE',
      phone: st.phone,
      designation: st.desig,
      department: st.dept,
      category: st.category,
      joiningDate: '2023-01-15',
      employmentStatus: 'ACTIVE',
      createdAt: now,
      updatedAt: now,
    };
    batch.set(doc(db, 'staff', sId), cleanFirestoreData(staffData));
  });

  // 7. Students: 20 students
  const studentNames = [
    { name: 'Aarav Sharma', gender: 'MALE' as const, father: 'Rajesh Sharma', mother: 'Pooja Sharma' },
    { name: 'Ananya Gupta', gender: 'FEMALE' as const, father: 'Deepak Gupta', mother: 'Seema Gupta' },
    { name: 'Vihaan Patel', gender: 'MALE' as const, father: 'Kiran Patel', mother: 'Geeta Patel' },
    { name: 'Diya Nair', gender: 'FEMALE' as const, father: 'Manoj Nair', mother: 'Saritha Nair' },
    { name: 'Ishaan Roy', gender: 'MALE' as const, father: 'Subhash Roy', mother: 'Bani Roy' },
    { name: 'Riya Sen', gender: 'FEMALE' as const, father: 'Debashish Sen', mother: 'Ruma Sen' },
    { name: 'Kabir Kapoor', gender: 'MALE' as const, father: 'Anil Kapoor', mother: 'Sunita Kapoor' },
    { name: 'Avani Deshmukh', gender: 'FEMALE' as const, father: 'Sanjay Deshmukh', mother: 'Shalini Deshmukh' },
    { name: 'Reyansh Malhotra', gender: 'MALE' as const, father: 'Vivek Malhotra', mother: 'Ritu Malhotra' },
    { name: 'Saisha Mehta', gender: 'FEMALE' as const, father: 'Nikhil Mehta', mother: 'Kavita Mehta' },
    { name: 'Advait Rao', gender: 'MALE' as const, father: 'Venkat Rao', mother: 'Lakshmi Rao' },
    { name: 'Myra Bhatia', gender: 'FEMALE' as const, father: 'Gaurav Bhatia', mother: 'Divya Bhatia' },
    { name: 'Dhruv Chauhan', gender: 'MALE' as const, father: 'Ravi Chauhan', mother: 'Anita Chauhan' },
    { name: 'Kavya Pillai', gender: 'FEMALE' as const, father: 'Hari Pillai', mother: 'Radha Pillai' },
    { name: 'Shaurya Tiwari', gender: 'MALE' as const, father: 'Santosh Tiwari', mother: 'Manju Tiwari' },
    { name: 'Tara Saxena', gender: 'FEMALE' as const, father: 'Pradeep Saxena', mother: 'Alka Saxena' },
    { name: 'Atharv Joshi', gender: 'MALE' as const, father: 'Kamlesh Joshi', mother: 'Nalini Joshi' },
    { name: 'Zoya Khan', gender: 'FEMALE' as const, father: 'Imran Khan', mother: 'Nasreen Khan' },
    { name: 'Kian Agarwal', gender: 'MALE' as const, father: 'Ashish Agarwal', mother: 'Neelam Agarwal' },
    { name: 'Navya Iyer', gender: 'FEMALE' as const, father: 'Gopal Iyer', mother: 'Meenakshi Iyer' },
  ];

  studentNames.forEach((st, idx) => {
    const sId = `student_demo_${idx + 1}`;
    const assignedClass = classDefs[idx % classDefs.length];
    const assignedSec = sectionDefs.find((s) => s.classId === assignedClass.id && s.name === (idx % 2 === 0 ? 'A' : 'B'))!;

    const studentData: Student = {
      id: sId,
      schoolId,
      admissionNumber: `ADM-2025-${(idx + 1).toString().padStart(3, '0')}`,
      rollNumber: `${(idx % 10) + 1}`,
      fullName: st.name,
      gender: st.gender,
      dateOfBirth: '2010-06-20',
      bloodGroup: ['A+', 'B+', 'O+', 'AB+'][idx % 4],
      sessionId,
      classId: assignedClass.id,
      sectionId: assignedSec ? assignedSec.id : sectionDefs[0].id,
      admissionDate: '2025-04-10',
      status: 'ACTIVE',
      fatherName: st.father,
      motherName: st.mother,
      fatherPhone: `+91 987000${(1000 + idx).toString().slice(1)}`,
      motherPhone: `+91 987001${(1000 + idx).toString().slice(1)}`,
      parentEmail: `parent.${idx + 1}@example.com`,
      address: `${100 + idx}, Civil Lines`,
      city: 'Metropolis',
      state: 'Delhi',
      pinCode: '110001',
      emergencyName: st.father,
      emergencyRelation: 'Father',
      emergencyPhone: `+91 987000${(1000 + idx).toString().slice(1)}`,
      createdAt: now,
      updatedAt: now,
    };
    batch.set(doc(db, 'students', sId), cleanFirestoreData(studentData));
  });

  // Update current session on school document
  batch.update(doc(db, 'schools', schoolId), {
    currentSessionId: sessionId,
    updatedAt: now,
  });

  await batch.commit();

  // Load Phase 2 Finance Demo Data
  await loadDemoFinanceData(schoolId, adminUserId, adminName, sessionId);

  await logAuditEvent({
    schoolId,
    userId: adminUserId,
    userName: adminName,
    userRole: 'ADMIN',
    action: 'DEMO_DATA_LOADED',
    module: 'System',
    description: 'Sample academic structure, 20 students, staff, and complete Phase 2 Finance module loaded successfully.',
  });
}

export async function loadDemoFinanceData(
  schoolId: string,
  adminUserId: string,
  adminName: string,
  sessionId: string = 'session_demo_2025_26'
): Promise<void> {
  const batch = writeBatch(db);
  const now = new Date().toISOString();
  const finYear = '2025-26';

  // 1. Institutional Financial Settings
  const finSettings: FinancialSettings = {
    id: schoolId,
    schoolId,
    financialYear: finYear,
    receiptPrefix: 'SCH',
    receiptStartingNumber: 1,
    currentReceiptCounter: 4,
    receiptNumberPattern: '{PREFIX}-{YEAR}-{NUM6}',
    currency: '₹',
    allowPartialPayments: true,
    allowAdvancePayments: true,
    defaultLateFeeType: 'PER_DAY',
    defaultLateFeeAmount: 20,
    defaultGracePeriodDays: 10,
    notificationPreferences: {
      feeDueReminder: true,
      feeOverdueReminder: true,
      paymentConfirmation: true,
      receiptNotification: true,
    },
    authorizedSignatoryName: 'Vikram Singh',
    authorizedSignatoryTitle: 'Chief Accountant',
    termsAndConditions: '1. Computer generated fee receipt does not require physical stamp.\n2. Fees once paid are non-transferable and non-refundable.\n3. Defaulter interest at ₹20/day is charged after the grace period.',
    createdAt: now,
    updatedAt: now,
  };
  batch.set(doc(db, 'financialSettings', schoolId), cleanFirestoreData(finSettings));

  // 2. Standard Expense Categories
  const expCats: ExpenseCategory[] = [
    { id: `exp_cat_util_${schoolId}`, schoolId, name: 'Electricity & Utilities', isDefault: true, createdAt: now },
    { id: `exp_cat_stat_${schoolId}`, schoolId, name: 'Stationery & Examination Printing', isDefault: true, createdAt: now },
    { id: `exp_cat_rep_${schoolId}`, schoolId, name: 'Campus Repairs & Maintenance', isDefault: true, createdAt: now },
    { id: `exp_cat_lab_${schoolId}`, schoolId, name: 'IT & Lab Equipment', isDefault: true, createdAt: now },
    { id: `exp_cat_welf_${schoolId}`, schoolId, name: 'Staff Welfare & Events', isDefault: true, createdAt: now },
  ];
  expCats.forEach((cat) => {
    batch.set(doc(db, 'expenseCategories', cat.id), cleanFirestoreData(cat));
  });

  // 3. Fee Structures
  const struct1: FeeStructure = {
    id: `fee_struct_c9_tui_${schoolId}`,
    schoolId,
    academicSessionId: sessionId,
    name: 'Class 9 Monthly Tuition Fee',
    classId: 'class_demo_c9',
    feeCategory: 'Tuition Fee',
    frequency: 'MONTHLY',
    amount: 1500,
    dueDateDay: 10,
    lateFeeRule: { type: 'PER_DAY', amount: 20, gracePeriodDays: 10 },
    status: 'ACTIVE',
    description: 'Mandatory regular classroom instructional fee for Class 9',
    createdAt: now,
    updatedAt: now,
    createdBy: adminUserId,
  };

  const struct2: FeeStructure = {
    id: `fee_struct_c9_ann_${schoolId}`,
    schoolId,
    academicSessionId: sessionId,
    name: 'Class 9 Annual Development Charges',
    classId: 'class_demo_c9',
    feeCategory: 'Annual Fee',
    frequency: 'ANNUAL',
    amount: 3000,
    dueDate: '2025-04-10',
    lateFeeRule: { type: 'PER_DAY', amount: 20, gracePeriodDays: 10 },
    status: 'ACTIVE',
    description: 'Campus facility development, library & sports facilities',
    createdAt: now,
    updatedAt: now,
    createdBy: adminUserId,
  };

  const struct3: FeeStructure = {
    id: `fee_struct_c10_tui_${schoolId}`,
    schoolId,
    academicSessionId: sessionId,
    name: 'Class 10 Monthly Tuition Fee',
    classId: 'class_demo_c10',
    feeCategory: 'Tuition Fee',
    frequency: 'MONTHLY',
    amount: 1500,
    dueDateDay: 10,
    lateFeeRule: { type: 'PER_DAY', amount: 20, gracePeriodDays: 10 },
    status: 'ACTIVE',
    description: 'Instructional curriculum fee for Class 10',
    createdAt: now,
    updatedAt: now,
    createdBy: adminUserId,
  };

  const struct4: FeeStructure = {
    id: `fee_struct_c11_tui_${schoolId}`,
    schoolId,
    academicSessionId: sessionId,
    name: 'Class 11 Science Tuition Fee',
    classId: 'class_demo_c11',
    feeCategory: 'Tuition Fee',
    frequency: 'MONTHLY',
    amount: 2200,
    dueDateDay: 10,
    lateFeeRule: { type: 'PER_DAY', amount: 20, gracePeriodDays: 10 },
    status: 'ACTIVE',
    description: 'Senior secondary instructional fee including lab sessions',
    createdAt: now,
    updatedAt: now,
    createdBy: adminUserId,
  };

  [struct1, struct2, struct3, struct4].forEach((str) => {
    batch.set(doc(db, 'feeStructures', str.id), cleanFirestoreData(str));
  });

  // 4. Fee Discounts
  const discount1: FeeDiscount = {
    id: `fee_disc_merit_${schoolId}`,
    schoolId,
    academicSessionId: sessionId,
    name: 'Merit Scholarship (Top Rankers)',
    type: 'PERCENTAGE',
    discountScope: 'CATEGORY',
    value: 20,
    applicableCategory: 'Tuition Fee',
    reason: 'Awarded for scoring >90% in previous academic evaluation',
    approvedBy: adminUserId,
    approvedByName: adminName,
    date: '2025-04-01',
    isActive: true,
    createdAt: now,
    updatedAt: now,
    createdBy: adminUserId,
  };
  batch.set(doc(db, 'feeDiscounts', discount1.id), cleanFirestoreData(discount1));

  // 5. Seed Real Student Fee Items
  // Student 1 (Aarav Sharma): Fully Paid for April & May (Tuition + Annual + Lab = 5000 + 2000 = 7000)
  const s1Items: FeeItem[] = [
    {
      id: `fee_item_s1_apr_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_1',
      feeStructureId: struct1.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 1500,
      paidAmount: 1500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s1_apr_ann`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_1',
      feeStructureId: struct2.id,
      feeCategory: 'Annual Fee',
      name: 'Annual Charges - 2025-26',
      period: '2025-26',
      dueDate: '2025-04-10',
      grossAmount: 3000,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 3000,
      paidAmount: 3000,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s1_apr_lab`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_1',
      feeCategory: 'Computer Fee',
      name: 'Computer Lab Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 500,
      paidAmount: 500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s1_may_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_1',
      feeStructureId: struct1.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - May 2025',
      period: 'May 2025',
      dueDate: '2025-05-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 1500,
      paidAmount: 1500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s1_may_lab`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_1',
      feeCategory: 'Computer Fee',
      name: 'Computer Lab Fee - May 2025',
      period: 'May 2025',
      dueDate: '2025-05-10',
      grossAmount: 500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 500,
      paidAmount: 500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s1_jun_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_1',
      feeStructureId: struct1.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - June 2025',
      period: 'June 2025',
      dueDate: '2025-06-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 1500,
      paidAmount: 0,
      balance: 1500,
      status: 'PENDING',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
  ];

  // Student 2 (Ananya Gupta): Paid April, Partial May (Paid 1000 of 1500 on May Tuition)
  const s2Items: FeeItem[] = [
    {
      id: `fee_item_s2_apr_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_2',
      feeStructureId: struct1.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 1500,
      paidAmount: 1500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s2_apr_ann`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_2',
      feeStructureId: struct2.id,
      feeCategory: 'Annual Fee',
      name: 'Annual Charges - 2025-26',
      period: '2025-26',
      dueDate: '2025-04-10',
      grossAmount: 3000,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 3000,
      paidAmount: 3000,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s2_apr_lab`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_2',
      feeCategory: 'Computer Fee',
      name: 'Computer Lab Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 500,
      paidAmount: 500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s2_may_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_2',
      feeStructureId: struct1.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - May 2025',
      period: 'May 2025',
      dueDate: '2025-05-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 1500,
      paidAmount: 1000,
      balance: 500,
      status: 'PARTIAL',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s2_may_lab`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_2',
      feeCategory: 'Computer Fee',
      name: 'Computer Lab Fee - May 2025',
      period: 'May 2025',
      dueDate: '2025-05-10',
      grossAmount: 500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 500,
      paidAmount: 500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
  ];

  // Student 3 (Vihaan Patel): 20% discount on Tuition -> Net 1200, paid 4700 in April
  const s3Items: FeeItem[] = [
    {
      id: `fee_item_s3_apr_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_3',
      feeStructureId: struct3.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 1500,
      discountAmount: 300,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 1200,
      paidAmount: 1200,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s3_apr_ann`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_3',
      feeCategory: 'Annual Fee',
      name: 'Annual Charges - 2025-26',
      period: '2025-26',
      dueDate: '2025-04-10',
      grossAmount: 3000,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 3000,
      paidAmount: 3000,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s3_apr_lab`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_3',
      feeCategory: 'Computer Fee',
      name: 'Computer Lab Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 0,
      netPayable: 500,
      paidAmount: 500,
      balance: 0,
      status: 'PAID',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
  ];

  // Student 4 (Diya Nair): Defaulter! Overdue April & May (>30 days overdue)
  const s4Items: FeeItem[] = [
    {
      id: `fee_item_s4_apr_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_4',
      feeStructureId: struct3.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 200,
      netPayable: 1700,
      paidAmount: 0,
      balance: 1700,
      status: 'OVERDUE',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s4_apr_ann`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_4',
      feeCategory: 'Annual Fee',
      name: 'Annual Development Charges - 2025-26',
      period: '2025-26',
      dueDate: '2025-04-10',
      grossAmount: 3000,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 300,
      netPayable: 3300,
      paidAmount: 0,
      balance: 3300,
      status: 'OVERDUE',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s4_may_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_4',
      feeStructureId: struct3.id,
      feeCategory: 'Tuition Fee',
      name: 'Tuition Fee - May 2025',
      period: 'May 2025',
      dueDate: '2025-05-10',
      grossAmount: 1500,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 100,
      netPayable: 1600,
      paidAmount: 0,
      balance: 1600,
      status: 'OVERDUE',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
  ];

  // Student 5 (Ishaan Roy - Class 11A): Defaulter!
  const s5Items: FeeItem[] = [
    {
      id: `fee_item_s5_apr_tui`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_5',
      feeStructureId: struct4.id,
      feeCategory: 'Tuition Fee',
      name: 'Class 11 Science Tuition - April 2025',
      period: 'April 2025',
      dueDate: '2025-04-10',
      grossAmount: 2200,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 200,
      netPayable: 2400,
      paidAmount: 0,
      balance: 2400,
      status: 'OVERDUE',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
    {
      id: `fee_item_s5_apr_ann`,
      schoolId,
      academicSessionId: sessionId,
      studentId: 'student_demo_5',
      feeCategory: 'Annual Fee',
      name: 'Class 11 Senior Annual Charges',
      period: '2025-26',
      dueDate: '2025-04-10',
      grossAmount: 4000,
      discountAmount: 0,
      concessionAmount: 0,
      lateFeeAmount: 400,
      netPayable: 4400,
      paidAmount: 0,
      balance: 4400,
      status: 'OVERDUE',
      createdAt: now,
      updatedAt: now,
      createdBy: adminUserId,
    },
  ];

  const allFeeItems = [...s1Items, ...s2Items, ...s3Items, ...s4Items, ...s5Items];
  allFeeItems.forEach((item) => {
    batch.set(doc(db, 'feeItems', item.id), cleanFirestoreData(item));
  });

  // 6. Payments & Printable Receipts
  // Receipt 1
  const rec1: Receipt = {
    id: `rec_demo_1`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    receiptNumber: 'SCH-2025-000001',
    paymentId: `pay_demo_1`,
    paymentDate: '2025-04-05',
    studentId: 'student_demo_1',
    studentName: 'Aarav Sharma',
    admissionNumber: 'ADM-2025-001',
    className: 'Class 9',
    sectionName: 'A',
    parentName: 'Rajesh Sharma',
    parentPhone: '+91 987000000',
    grossAmount: 7000,
    discountAmount: 0,
    lateFeeAmount: 0,
    netPaid: 7000,
    advanceAmount: 0,
    previousBalance: 7000,
    remainingBalance: 0,
    paymentMode: 'UPI',
    referenceNumber: 'UPI-SBI-8899112233',
    remarks: 'April & May term fee cleared online via UPI',
    status: 'ACTIVE',
    authorizedSignature: 'Vikram Singh',
    items: [
      { feeItemId: 'fee_item_s1_apr_tui', feeType: 'Tuition Fee', period: 'April 2025', amount: 1500, discount: 0, lateFee: 0, paid: 1500, remaining: 0 },
      { feeItemId: 'fee_item_s1_apr_ann', feeType: 'Annual Fee', period: '2025-26', amount: 3000, discount: 0, lateFee: 0, paid: 3000, remaining: 0 },
      { feeItemId: 'fee_item_s1_apr_lab', feeType: 'Computer Fee', period: 'April 2025', amount: 500, discount: 0, lateFee: 0, paid: 500, remaining: 0 },
      { feeItemId: 'fee_item_s1_may_tui', feeType: 'Tuition Fee', period: 'May 2025', amount: 1500, discount: 0, lateFee: 0, paid: 1500, remaining: 0 },
      { feeItemId: 'fee_item_s1_may_lab', feeType: 'Computer Fee', period: 'May 2025', amount: 500, discount: 0, lateFee: 0, paid: 500, remaining: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  };
  const pay1: FeePayment = {
    id: `pay_demo_1`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    studentId: 'student_demo_1',
    receiptId: rec1.id,
    receiptNumber: rec1.receiptNumber,
    paymentDate: rec1.paymentDate,
    grossAmount: 7000,
    discountAmount: 0,
    lateFeeAmount: 0,
    netPayable: 7000,
    amountReceived: 7000,
    allocatedAmount: 7000,
    advanceAmount: 0,
    previousBalance: 7000,
    remainingBalance: 0,
    paymentMode: 'UPI',
    referenceNumber: 'UPI-SBI-8899112233',
    remarks: 'Full settlement for April and May',
    status: 'COMPLETED',
    collectedBy: adminUserId,
    collectedByName: 'Vikram Singh',
    createdAt: now,
    updatedAt: now,
  };

  // Receipt 2
  const rec2: Receipt = {
    id: `rec_demo_2`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    receiptNumber: 'SCH-2025-000002',
    paymentId: `pay_demo_2`,
    paymentDate: '2025-04-08',
    studentId: 'student_demo_2',
    studentName: 'Ananya Gupta',
    admissionNumber: 'ADM-2025-002',
    className: 'Class 9',
    sectionName: 'A',
    parentName: 'Deepak Gupta',
    parentPhone: '+91 987000001',
    grossAmount: 7000,
    discountAmount: 0,
    lateFeeAmount: 0,
    netPaid: 6500,
    advanceAmount: 0,
    previousBalance: 7000,
    remainingBalance: 500,
    paymentMode: 'CASH',
    remarks: 'Partial fee payment received at counter',
    status: 'ACTIVE',
    authorizedSignature: 'Vikram Singh',
    items: [
      { feeItemId: 'fee_item_s2_apr_tui', feeType: 'Tuition Fee', period: 'April 2025', amount: 1500, discount: 0, lateFee: 0, paid: 1500, remaining: 0 },
      { feeItemId: 'fee_item_s2_apr_ann', feeType: 'Annual Fee', period: '2025-26', amount: 3000, discount: 0, lateFee: 0, paid: 3000, remaining: 0 },
      { feeItemId: 'fee_item_s2_apr_lab', feeType: 'Computer Fee', period: 'April 2025', amount: 500, discount: 0, lateFee: 0, paid: 500, remaining: 0 },
      { feeItemId: 'fee_item_s2_may_tui', feeType: 'Tuition Fee', period: 'May 2025', amount: 1500, discount: 0, lateFee: 0, paid: 1000, remaining: 500 },
      { feeItemId: 'fee_item_s2_may_lab', feeType: 'Computer Fee', period: 'May 2025', amount: 500, discount: 0, lateFee: 0, paid: 500, remaining: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  };
  const pay2: FeePayment = {
    id: `pay_demo_2`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    studentId: 'student_demo_2',
    receiptId: rec2.id,
    receiptNumber: rec2.receiptNumber,
    paymentDate: rec2.paymentDate,
    grossAmount: 7000,
    discountAmount: 0,
    lateFeeAmount: 0,
    netPayable: 7000,
    amountReceived: 6500,
    allocatedAmount: 6500,
    advanceAmount: 0,
    previousBalance: 7000,
    remainingBalance: 500,
    paymentMode: 'CASH',
    remarks: '₹500 remaining on May tuition',
    status: 'COMPLETED',
    collectedBy: adminUserId,
    collectedByName: 'Vikram Singh',
    createdAt: now,
    updatedAt: now,
  };

  // Receipt 3
  const rec3: Receipt = {
    id: `rec_demo_3`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    receiptNumber: 'SCH-2025-000003',
    paymentId: `pay_demo_3`,
    paymentDate: '2025-04-10',
    studentId: 'student_demo_3',
    studentName: 'Vihaan Patel',
    admissionNumber: 'ADM-2025-003',
    className: 'Class 10',
    sectionName: 'A',
    parentName: 'Kiran Patel',
    parentPhone: '+91 987000002',
    grossAmount: 5000,
    discountAmount: 300,
    lateFeeAmount: 0,
    netPaid: 4700,
    advanceAmount: 0,
    previousBalance: 4700,
    remainingBalance: 0,
    paymentMode: 'CHEQUE',
    referenceNumber: 'CHQ-882109',
    remarks: 'Cheque cleared, 20% Merit discount honored',
    status: 'ACTIVE',
    authorizedSignature: 'Vikram Singh',
    items: [
      { feeItemId: 'fee_item_s3_apr_tui', feeType: 'Tuition Fee', period: 'April 2025', amount: 1500, discount: 300, lateFee: 0, paid: 1200, remaining: 0 },
      { feeItemId: 'fee_item_s3_apr_ann', feeType: 'Annual Fee', period: '2025-26', amount: 3000, discount: 0, lateFee: 0, paid: 3000, remaining: 0 },
      { feeItemId: 'fee_item_s3_apr_lab', feeType: 'Computer Fee', period: 'April 2025', amount: 500, discount: 0, lateFee: 0, paid: 500, remaining: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  };
  const pay3: FeePayment = {
    id: `pay_demo_3`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    studentId: 'student_demo_3',
    receiptId: rec3.id,
    receiptNumber: rec3.receiptNumber,
    paymentDate: rec3.paymentDate,
    grossAmount: 5000,
    discountAmount: 300,
    lateFeeAmount: 0,
    netPayable: 4700,
    amountReceived: 4700,
    allocatedAmount: 4700,
    advanceAmount: 0,
    previousBalance: 4700,
    remainingBalance: 0,
    paymentMode: 'CHEQUE',
    referenceNumber: 'CHQ-882109',
    remarks: 'HDFC Bank Cheque Cleared',
    status: 'COMPLETED',
    collectedBy: adminUserId,
    collectedByName: 'Vikram Singh',
    createdAt: now,
    updatedAt: now,
  };

  // Receipt 4 (Cancelled receipt for audit testing)
  const rec4: Receipt = {
    id: `rec_demo_4`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    receiptNumber: 'SCH-2025-000004',
    paymentId: `pay_demo_4`,
    paymentDate: '2025-04-12',
    studentId: 'student_demo_4',
    studentName: 'Diya Nair',
    admissionNumber: 'ADM-2025-004',
    className: 'Class 10',
    sectionName: 'A',
    parentName: 'Manoj Nair',
    grossAmount: 2000,
    discountAmount: 0,
    lateFeeAmount: 0,
    netPaid: 2000,
    advanceAmount: 0,
    previousBalance: 2000,
    remainingBalance: 0,
    paymentMode: 'CASH',
    remarks: 'Mistakenly entered cash payment',
    status: 'CANCELLED',
    cancelledAt: '2025-04-15T10:30:00Z',
    cancelledBy: adminUserId,
    cancelledByName: 'Vikram Singh',
    cancellationReason: 'Wrong student ledger selected during counter cash entry',
    items: [
      { feeItemId: 'fee_item_s4_apr_tui', feeType: 'Tuition Fee', period: 'April 2025', amount: 2000, discount: 0, lateFee: 0, paid: 2000, remaining: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  };
  const pay4: FeePayment = {
    id: `pay_demo_4`,
    schoolId,
    academicSessionId: sessionId,
    financialYear: finYear,
    studentId: 'student_demo_4',
    receiptId: rec4.id,
    receiptNumber: rec4.receiptNumber,
    paymentDate: rec4.paymentDate,
    grossAmount: 2000,
    discountAmount: 0,
    lateFeeAmount: 0,
    netPayable: 2000,
    amountReceived: 2000,
    allocatedAmount: 2000,
    advanceAmount: 0,
    previousBalance: 2000,
    remainingBalance: 0,
    paymentMode: 'CASH',
    status: 'CANCELLED',
    cancelledAt: '2025-04-15T10:30:00Z',
    cancelledBy: adminUserId,
    cancellationReason: 'Wrong student ledger selected during counter cash entry',
    collectedBy: adminUserId,
    collectedByName: 'Vikram Singh',
    createdAt: now,
    updatedAt: now,
  };

  [rec1, rec2, rec3, rec4].forEach((r) => batch.set(doc(db, 'receipts', r.id), cleanFirestoreData(r)));
  [pay1, pay2, pay3, pay4].forEach((p) => batch.set(doc(db, 'feePayments', p.id), cleanFirestoreData(p)));

  // 7. Expenses
  const exp1: Expense = {
    id: `exp_demo_1`,
    schoolId,
    financialYear: finYear,
    date: '2025-04-15',
    category: 'Electricity & Utilities',
    description: 'Main Campus Monthly Electricity Tariff (BSES)',
    amount: 12500,
    paymentMode: 'BANK_TRANSFER',
    referenceNumber: 'NEFT-AXIS-9921827',
    vendorPayee: 'BSES Rajdhani Power Ltd',
    status: 'PAID',
    submittedBy: adminUserId,
    submittedByName: 'Vikram Singh',
    approvedBy: adminUserId,
    approvedByName: adminName,
    approvedAt: '2025-04-15T09:00:00Z',
    paidAt: '2025-04-15T11:00:00Z',
    createdAt: now,
    updatedAt: now,
  };

  const exp2: Expense = {
    id: `exp_demo_2`,
    schoolId,
    financialYear: finYear,
    date: '2025-04-18',
    category: 'Stationery & Examination Printing',
    description: 'First Term Examination Answer Booklets & Printing',
    amount: 4800,
    paymentMode: 'CASH',
    referenceNumber: 'VOUCHER-0482',
    vendorPayee: 'National Press & Printers',
    status: 'PAID',
    submittedBy: adminUserId,
    submittedByName: 'Vikram Singh',
    approvedBy: adminUserId,
    approvedByName: adminName,
    approvedAt: '2025-04-18T10:00:00Z',
    paidAt: '2025-04-18T12:00:00Z',
    createdAt: now,
    updatedAt: now,
  };

  const exp3: Expense = {
    id: `exp_demo_3`,
    schoolId,
    financialYear: finYear,
    date: '2025-04-20',
    category: 'IT & Lab Equipment',
    description: 'Campus High-Speed Dedicated Internet Lease Line',
    amount: 2360,
    paymentMode: 'UPI',
    referenceNumber: 'UPI-AIRTEL-881923',
    vendorPayee: 'Airtel Enterprise Solutions',
    status: 'PAID',
    submittedBy: adminUserId,
    submittedByName: 'Vikram Singh',
    approvedBy: adminUserId,
    approvedByName: adminName,
    approvedAt: '2025-04-20T10:00:00Z',
    paidAt: '2025-04-20T11:30:00Z',
    createdAt: now,
    updatedAt: now,
  };

  const exp4: Expense = {
    id: `exp_demo_4`,
    schoolId,
    financialYear: finYear,
    date: '2025-04-22',
    category: 'IT & Lab Equipment',
    description: 'Chemistry & Physics Laboratory Glassware and Consumables',
    amount: 6800,
    paymentMode: 'BANK_TRANSFER',
    vendorPayee: 'Modern Scientific Supplies',
    status: 'APPROVED',
    submittedBy: adminUserId,
    submittedByName: 'Vikram Singh',
    approvedBy: adminUserId,
    approvedByName: adminName,
    approvedAt: '2025-04-22T14:00:00Z',
    createdAt: now,
    updatedAt: now,
  };

  const exp5: Expense = {
    id: `exp_demo_5`,
    schoolId,
    financialYear: finYear,
    date: '2025-04-24',
    category: 'Staff Welfare & Events',
    description: 'Annual Inter-House Sports Day Medals & Certificates',
    amount: 15000,
    paymentMode: 'CHEQUE',
    vendorPayee: 'Champion Sports Delhi',
    status: 'PENDING_APPROVAL',
    submittedBy: adminUserId,
    submittedByName: 'Vikram Singh',
    createdAt: now,
    updatedAt: now,
  };

  [exp1, exp2, exp3, exp4, exp5].forEach((e) => batch.set(doc(db, 'expenses', e.id), cleanFirestoreData(e)));

  // 8. Cash Book Entries with verified Running Balance
  // Balance progression:
  // Initial Capital: +25000 => 25000
  // Rec 1 (UPI): +7000 => 32000
  // Rec 2 (CASH): +6500 => 38500
  // Rec 3 (CHQ): +4700 => 43200
  // Rec 4 (CASH): +2000 => 45200
  // Cancel Rec 4: -2000 => 43200
  // Exp 1: -12500 => 30700
  // Exp 2: -4800 => 25900
  // Exp 3: -2360 => 23540
  const cashEntries: CashBookEntry[] = [
    {
      id: `cb_entry_1`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-01',
      description: 'Opening Imprest / Cash Reserve',
      type: 'INCOME',
      referenceType: 'ADJUSTMENT',
      referenceId: 'OPENING',
      receiptPaymentNumber: 'INIT-2025-01',
      income: 25000,
      expense: 0,
      runningBalance: 25000,
      paymentMode: 'CASH',
      createdAt: now,
    },
    {
      id: `cb_entry_2`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-05',
      description: 'Fee collection - Aarav Sharma (Class 9A)',
      type: 'INCOME',
      referenceType: 'PAYMENT',
      referenceId: rec1.id,
      receiptPaymentNumber: rec1.receiptNumber,
      income: 7000,
      expense: 0,
      runningBalance: 32000,
      paymentMode: 'UPI',
      createdAt: now,
    },
    {
      id: `cb_entry_3`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-08',
      description: 'Fee collection - Ananya Gupta (Class 9A)',
      type: 'INCOME',
      referenceType: 'PAYMENT',
      referenceId: rec2.id,
      receiptPaymentNumber: rec2.receiptNumber,
      income: 6500,
      expense: 0,
      runningBalance: 38500,
      paymentMode: 'CASH',
      createdAt: now,
    },
    {
      id: `cb_entry_4`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-10',
      description: 'Fee collection - Vihaan Patel (Class 10A)',
      type: 'INCOME',
      referenceType: 'PAYMENT',
      referenceId: rec3.id,
      receiptPaymentNumber: rec3.receiptNumber,
      income: 4700,
      expense: 0,
      runningBalance: 43200,
      paymentMode: 'CHEQUE',
      createdAt: now,
    },
    {
      id: `cb_entry_5`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-12',
      description: 'Fee collection - Diya Nair (Class 10A)',
      type: 'INCOME',
      referenceType: 'PAYMENT',
      referenceId: rec4.id,
      receiptPaymentNumber: rec4.receiptNumber,
      income: 2000,
      expense: 0,
      runningBalance: 45200,
      paymentMode: 'CASH',
      createdAt: now,
    },
    {
      id: `cb_entry_6`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-15',
      description: 'Reverse entry: Receipt SCH-2025-000004 cancelled',
      type: 'EXPENSE',
      referenceType: 'PAYMENT',
      referenceId: rec4.id,
      receiptPaymentNumber: `REV-${rec4.receiptNumber}`,
      income: 0,
      expense: 2000,
      runningBalance: 43200,
      paymentMode: 'CASH',
      createdAt: now,
    },
    {
      id: `cb_entry_7`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-15',
      description: 'Disbursement: Main Campus Electricity Bill (BSES)',
      type: 'EXPENSE',
      referenceType: 'EXPENSE',
      referenceId: exp1.id,
      receiptPaymentNumber: 'EXP-2025-01',
      income: 0,
      expense: 12500,
      runningBalance: 30700,
      paymentMode: 'BANK_TRANSFER',
      createdAt: now,
    },
    {
      id: `cb_entry_8`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-18',
      description: 'Disbursement: Exam Question Papers Printing',
      type: 'EXPENSE',
      referenceType: 'EXPENSE',
      referenceId: exp2.id,
      receiptPaymentNumber: 'EXP-2025-02',
      income: 0,
      expense: 4800,
      runningBalance: 25900,
      paymentMode: 'CASH',
      createdAt: now,
    },
    {
      id: `cb_entry_9`,
      schoolId,
      financialYear: finYear,
      date: '2025-04-20',
      description: 'Disbursement: Campus Fiber Internet Line',
      type: 'EXPENSE',
      referenceType: 'EXPENSE',
      referenceId: exp3.id,
      receiptPaymentNumber: 'EXP-2025-03',
      income: 0,
      expense: 2360,
      runningBalance: 23540,
      paymentMode: 'UPI',
      createdAt: now,
    },
  ];

  cashEntries.forEach((entry) => {
    batch.set(doc(db, 'cashBook', entry.id), cleanFirestoreData(entry));
  });

  await batch.commit();
}

export async function seedDemoData(
  schoolId: string,
  adminUserId: string = 'system_admin',
  adminName: string = 'System Admin'
): Promise<void> {
  return loadDemoSchoolData(schoolId, adminUserId, adminName);
}
